function display(s)
% DISPLAY - Command window display of DMRG system
%   
  disp('DMRG SYSTEM:')
  disp('system length =')
  disp(s.L)
  disp('left block length =')
  disp(s.l)
  disp('left block Hamiltonian =')
  disp(s.HL)
  disp('interaction left block - middle sites =')
  disp(s.hLM)
  disp('middle sites Hamiltonian =')
  disp(s.hM)
  disp('interaction middle sites - right block =')
  disp(s.hMR)
  disp('right block Hamiltonian =')
  disp(s.HR)
  disp('left block transformation matrix =')
  disp(s.WL)
  disp('right block transformation matrix =')
  disp(s.WR)
